# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epoch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TenhouGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=255, unique=True)),
                ('epoch', models.CharField(max_length=255)),
                ('when_played', models.DateTimeField()),
                ('lobby', models.IntegerField()),
                ('scores', models.CharField(blank=True, max_length=255)),
                ('url_names', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
